# Generated by Django 2.2 on 2020-02-18 14:49

import autoParts.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoParts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logocategory',
            options={'verbose_name': 'logo', 'verbose_name_plural': 'logo'},
        ),
        migrations.AddField(
            model_name='partcategory',
            name='imgName',
            field=models.ImageField(default='', upload_to=autoParts.models.save_img, verbose_name='logo图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='createDatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 18, 22, 49, 37, 903718), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='imgName',
            field=models.ImageField(blank=True, upload_to=autoParts.models.save_img, verbose_name='物品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pLogoCategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pLogoCategory_set', to='autoParts.LogoCategory', verbose_name='logo分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pPartCategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pPartCategory_set', to='autoParts.PartCategory', verbose_name='部位分类'),
        ),
    ]
