# Generated by Django 2.2 on 2020-02-18 14:52

import autoParts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoParts', '0002_auto_20200218_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partcategory',
            name='imgName',
        ),
        migrations.AddField(
            model_name='logocategory',
            name='imgName',
            field=models.ImageField(default='', upload_to=autoParts.models.save_img, verbose_name='logo图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='createDatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 18, 22, 52, 34, 303260), verbose_name='创建时间'),
        ),
    ]
