# Generated by Django 2.2 on 2020-03-10 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoParts', '0003_auto_20200218_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='createDatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 10, 10, 56, 51, 959542), verbose_name='创建时间'),
        ),
    ]
