# Generated by Django 2.2 on 2020-03-11 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoParts', '0004_auto_20200310_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='createDatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 17, 42, 1, 907909), verbose_name='创建时间'),
        ),
    ]
