# Generated by Django 2.2 on 2020-02-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('username', models.CharField(blank=True, default='', max_length=25, verbose_name='用户名')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='余额')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('tel', models.CharField(blank=True, default='', max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
