# Generated by Django 2.2 on 2020-03-10 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addName', models.CharField(max_length=255, verbose_name='地址')),
                ('addNameUser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='addNameUser_set', to='user.User', verbose_name='用户-地址')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
            },
        ),
    ]
