# Generated by Django 2.2 on 2020-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyAccount', models.CharField(blank=True, default='', max_length=20, verbose_name='购买用的账号')),
                ('buyGoods', models.CharField(blank=True, default='', max_length=20, verbose_name='购买的物品')),
                ('buyAddress', models.CharField(blank=True, default='', max_length=255, verbose_name='购买用的地址')),
                ('buyTel', models.CharField(blank=True, default='', max_length=11, verbose_name='购买用的电话')),
            ],
            options={
                'verbose_name': '购买记录',
                'verbose_name_plural': '购买记录',
            },
        ),
    ]
